---
version: "3.8"

services:
  back:
    command: npm run dev
    volumes:
      - ./src:/app/src

#  front-react:
#    command: npm start
#    ports:
#      - "8080:8080"
#    stdin_open: true
#    tty: true
#    volumes:
#      - '../../front/task-manager/src:/app/src'
